language: node_js

node_js:
  - 10
  - 9
  - 8
  - 7

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g @commitlint/travis-cli

install:
  - npm install
  - npm install -g codecov
  - npm install -g eslint
  - npm install --save redux
  - commitlint-travis

script:
  - npm run lint
  - npm run test
  - npm run build
  - codecov

notifications:
  email:
    on_failure: change

# after_success: 'npm run coveralls'

cache:
  directories:
    - node_modules
