language: elixir
elixir:
  - 1.9
otp_release:
  - 21.0
addons:
  postgresql: '9.6'
  apt:
    packages:
      # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves
      - libgconf-2-4

before_install:
  - sudo chown -R travis ./travis/install_node.sh
  - sudo chmod +x ./travis/install_node.sh
  - ./travis/install_node.sh

install:
  # web related
  - npm install
  # - npm install -g codecov
  # elixir/phoenix env
  - mix local.rebar --force > /dev/null
  - mix local.hex --force > /dev/null

before_script:
  - sudo chown -R travis ./travis/pull_server.sh
  - sudo chmod +x ./travis/pull_server.sh
  - ./travis/pull_server.sh

script:
  # - codecov
  - rm -rf .next
  - chmod +x ./utils/bin/jq-linux
  - ./utils/bin/jq-linux -s '.[0] * .[1]' config/config.json config/config.ci.json > /tmp/config.json
  - cp /tmp/config.json ./config/config.json
  - nvm exec 12.18.0 npm run build.ci
  - nvm exec 12.18.0 npm run test:ci

cache:
  directories:
    - ~/.cache
    - node_modules
    - _build
    - dep

notifications:
  email:
    on_failure: change
# after_success: 'npm run coveralls'
